services:
  - type: web
    name: storyteller-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    branch: main
    envVars:
      - key: NODE_VERSION
        value: 16
      - key: REACT_APP_API_URL
        value: https://storyteller-backend-liry.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 