services:
  - type: web
    name: storyteller-frontend
    env: static
    buildCommand: chmod +x build.sh && ./build.sh
    staticPublishPath: ./build
    runtime: node
    nodeVersion: 16
    envVars:
      - key: REACT_APP_API_URL
        value: https://storyteller-backend-liry.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 