import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiService } from "../services/apiService";
import storytellerLogo from "../images/storytellerlogo.png";
import "../styles/Home.css";

const Home = () => {
  const navigate = useNavigate();
  const [apiStatus, setApiStatus] = useState({ checked: false, online: false });
  const [error, setError] = useState("");

  useEffect(() => {
    const checkApiStatus = async () => {
      try {
        await apiService.checkStatus();
        setApiStatus({ checked: true, online: true });
      } catch (error) {
        console.error("API Status Error:", error);
        setApiStatus({ checked: true, online: false });
        setError(
          "Failed to connect to the StoryTeller API server. Please make sure the server is running."
        );
      }
    };

    checkApiStatus();
  }, []);

  return (
    <div className="home">
      {error && <div className="error">{error}</div>}

      <div className="hero-section">
        <div className="logo-container">
          <img
            src={storytellerLogo}
            alt="StoryTeller Logo"
            className="app-logo"
          />
        </div>

        <div className="welcome-content">
          <h1 className="hero-title">Welcome to StoryTeller</h1>
          <p className="hero-subtitle">
            Experience AI-generated interactive stories tailored to your
            choices. Create a unique character and embark on a personalized
            adventure.
          </p>
          <p className="hero-description">
            Explore fantasy worlds, cultivation realms, magical academies, and
            more!
          </p>

          <div className="action-buttons">
            <button
              className="btn btn-accent btn-large"
              onClick={() => navigate("/new-story")}
              disabled={!apiStatus.online}
            >
              <span className="btn-icon">✨</span>
              Create New Story
            </button>
            <button
              className="btn btn-secondary btn-large"
              onClick={() => navigate("/stories")}
              disabled={!apiStatus.online}
            >
              <span className="btn-icon">📚</span>
              My Stories
            </button>
          </div>
        </div>
      </div>

      {!apiStatus.checked && (
        <div className="loading">
          <div className="spinner"></div>
        </div>
      )}

      {apiStatus.checked && !apiStatus.online && (
        <div className="card api-status-card">
          <h3>API Server Offline</h3>
          <p>
            The StoryTeller API server appears to be offline. Please make sure
            it's running.
          </p>
          <p>To start the API server, run:</p>
          <pre>python storyteller-python/api_server.py</pre>
        </div>
      )}

      <section className="features-section">
        <div className="features-header">
          <h2>Why Choose StoryTeller?</h2>
          <p>Discover the features that make your adventure unique</p>
        </div>

        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon-container">
              <span className="feature-icon">🌟</span>
            </div>
            <h3>AI-Powered Stories</h3>
            <p>
              Experience unique, richly detailed stories generated by advanced
              AI technology that adapts to your choices.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-container">
              <span className="feature-icon">🏯</span>
            </div>
            <h3>Multiple Settings</h3>
            <p>
              Explore cultivation worlds, fantasy realms, magical academies, and
              many other immersive environments.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-container">
              <span className="feature-icon">👤</span>
            </div>
            <h3>Customizable Characters</h3>
            <p>
              Create your character with different origins, power systems, and
              backgrounds to shape your journey.
            </p>
          </div>

          <div className="feature-card">
            <div className="feature-icon-container">
              <span className="feature-icon">🔄</span>
            </div>
            <h3>Meaningful Choices</h3>
            <p>
              Your decisions shape the story and lead to different outcomes,
              creating a truly personalized experience.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default Home;
