import React, { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiService } from "../services/apiService";
import "../styles/Home.css";

const Home = () => {
  const navigate = useNavigate();
  const [apiStatus, setApiStatus] = useState({ checked: false, online: false });
  const [error, setError] = useState("");

  useEffect(() => {
    const checkApiStatus = async () => {
      try {
        await apiService.checkStatus();
        setApiStatus({ checked: true, online: true });
      } catch (error) {
        console.error("API Status Error:", error);
        setApiStatus({ checked: true, online: false });
        setError(
          "Failed to connect to the StoryTeller API server. Please make sure the server is running."
        );
      }
    };

    checkApiStatus();
  }, []);

  return (
    <div className="home">
      {error && <div className="error">{error}</div>}

      <div className="card welcome-card">
        <h2>Welcome to StoryTeller</h2>
        <p>
          Experience AI-generated interactive stories tailored to your choices.
          Create a unique character and embark on a personalized adventure.
        </p>
        <p>
          Explore fantasy worlds, cultivation realms, magical academies, and
          more!
        </p>

        <div className="action-buttons">
          <button
            className="btn btn-accent"
            onClick={() => navigate("/new-story")}
            disabled={!apiStatus.online}
          >
            Create New Story
          </button>
          <button
            className="btn"
            onClick={() => navigate("/stories")}
            disabled={!apiStatus.online}
          >
            Continue Story
          </button>
        </div>
      </div>

      {!apiStatus.checked && (
        <div className="loading">
          <div className="spinner"></div>
        </div>
      )}

      {apiStatus.checked && !apiStatus.online && (
        <div className="card api-status-card">
          <h3>API Server Offline</h3>
          <p>
            The StoryTeller API server appears to be offline. Please make sure
            it's running.
          </p>
          <p>To start the API server, run:</p>
          <pre>python storyteller-python/api_server.py</pre>
        </div>
      )}

      <div className="card features-card">
        <h3>Features</h3>
        <ul className="features-list">
          <li>
            <span className="feature-icon">🌟</span>
            <div>
              <h4>AI-Powered Stories</h4>
              <p>
                Experience unique, richly detailed stories generated by advanced
                AI
              </p>
            </div>
          </li>
          <li>
            <span className="feature-icon">🏯</span>
            <div>
              <h4>Multiple Settings</h4>
              <p>
                Explore cultivation worlds, fantasy realms, magical academies,
                and more
              </p>
            </div>
          </li>
          <li>
            <span className="feature-icon">👤</span>
            <div>
              <h4>Customizable Characters</h4>
              <p>
                Create your character with different origins, power systems, and
                backgrounds
              </p>
            </div>
          </li>
          <li>
            <span className="feature-icon">🔄</span>
            <div>
              <h4>Meaningful Choices</h4>
              <p>
                Your decisions shape the story and lead to different outcomes
              </p>
            </div>
          </li>
        </ul>
      </div>
    </div>
  );
};

export default Home;
